encyclopedia/urls.py
from django.urls import path

from . import views

app_name="Wiki"
urlpatterns = [
    path("", views.index, name="index"),
    path("wiki/<str:entry>", views.entryPage, name="entryPage"),
    path("search/", views.search, name="search"),
    path("add/", views.add, name="add"),
    path("edit/<str:entry>",views.edit, name="edit"),
    path("feelLucky/", views.random, name="random")
    
]

wiki/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("encyclopedia.urls"))
]

encyclopedia/models.py
from django.db import models

# Create your models here.

encyclopedia/views.py
from django.shortcuts import render
from django.http import HttpResponse
from markdown2 import Markdown
from django import forms
from . import util

class NewWikiPage(forms.Form):
      title = forms.CharField(label="title")
      content = forms.CharField(widget=forms.Textarea)
      
def index(request):
    return render(request, "encyclopedia/index.html", {
        "entries": util.list_entries()
    })

def entryPage(request,entry):
    markdowner = Markdown()
    if entry in util.list_entries():
        return(HttpResponse(markdowner.convert(util.get_entry(entry))))
    else:
        return (HttpResponse("page doesn't exist"))

def newPage(request):
    return HttpResponse("create a new page")

def search(request):
    markdowner = Markdown()
    entry = request.POST.get("entry", "")
    search_result = []
    if entry in util.list_entries():
        return(HttpResponse(markdowner.convert(util.get_entry(entry))))
    else:
        for iterator in util.list_entries():
            if(entry.lower() in iterator.lower()):
                search_result.append(iterator)
        return render(request,"encyclopedia/searchResult.html",{
            "entries":search_result
        })

# def add(request):
#     return render(request,"encyclopedia/addPage.html",{"form":NewWikiPage()
#     })

def add(request):
    if request.method == "POST":
       form = NewWikiPage(request.POST)
       if form.is_valid():
           title = form.cleaned_data["title"]
           content = form.cleaned_data["content"]
        #check if title duplicated
           if title in util.list_entries():
               return HttpResponse("The title duplicated with an existing wiki page")
           else:
                util.save_entry(title,content)
                return entryPage(request,title)
    return render(request,"encyclopedia/addPage.html",{"form":NewWikiPage()})
           #save the wikipage

def edit(request,entry):
    field = {"title":entry,"content":util.get_entry(entry)}
    form = NewWikiPage(field)
    
    if request.method == "POST":
        form = NewWikiPage(request.POST)
        if form.is_valid():
            content = form.cleaned_data["content"]
            title = form.cleaned_data["title"]
            util.save_entry(title=title,content=content)
            return entryPage(request,entry)
    return render(request,"encyclopedia/editPage.html",{"form":form, "entry":entry})
    #return render(request,"encyclopedia/editPage.html")
    #return HttpResponse(entry)
            
def random(request):
    import random
    randomNum = random.randint(0, len(util.list_entries())-1)
    #randomNum = random.randint(0,2)
    #random.seed()
    #randomNum = random.randRange(start=0,stop=len(util.list_entries))
    return entryPage(request,util.list_entries()[randomNum])

encyclopedia/templates/encyclopedia/addPage.html
{% extends "encyclopedia/layout.html" %}
{% block title%}
    Add new wiki page
{%endblock%}

{%block body%}
    <h1> Create a new wiki page </h1>
    <div class ="form-group">
    <form action="{%url 'Wiki:add' %}" method=post>
    {%csrf_token%}
    {{ form }}
    {% comment %} <textarea class="form-control" rows="10">
    </textarea> {% endcomment %}
    <button class="btn-primary">
    submit
    </button>
    </form>
    </div>
{%endblock%}

encyclopedia/templates/encyclopedia/editPage.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Edit Wiki Page
{%endblock%}

{%block body%}
    <h1>edit the wiki page</h1>
    <form action="{%url 'Wiki:edit' entry%}" method = POST>
    {%csrf_token%}
    {{form}}
    <button class="btn-primary">
    save
    </button>
    </form>
{%endblock%}

encyclopedia/templates/encyclopedia/index.html
{% extends "encyclopedia/layout.html" %}

{% block title %}
    Encyclopedia
{% endblock %}

{% block body %}

    <h1>All Pages</h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'Wiki:entryPage' entry %}"> {{ entry }}</a> 
            <form action="{%url 'Wiki:edit' entry%}">
            <button class="btn-primary"}>Edit</button> 
            </form>
            </li>
        {% endfor %}
    </ul>

{% endblock %}

encyclopedia/templates/encyclopedia/layout.html
{% load static %}

<!DOCTYPE html>

<html lang="en">
    <head>
        <title>{% block title %}{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css" integrity="sha384-Vkoo8x4CGsO3+Hhxv8T/Q5PaXtkKtu6ug5TOeNV6gBiFeWPGFN9MuhOf23Q9Ifjh" crossorigin="anonymous">
        <link href="{% static 'encyclopedia/styles.css' %}" rel="stylesheet">
    </head>
    <body>
        <!-- a navigation bar -->
        <!-- <nav class = "navbar navbar-expand-lg navbar-light bg-ligt">
            <a class = "navbar-brand" href="#"> Wiki</a>
            <button class = "navbar-toggler" type = "button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <form class="form-inline ml-auto">
                <input class="form-control" type="search" placeholder="Search" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Search</button>
            </form>
        </nav> -->
        <!-- end of navigation bar -->
        <div class="row">
            <div class="sidebar col-lg-2 col-md-3">
                <h2>Wiki</h2>
                <form action="{%url 'Wiki:search'%}" method="post">
                    {%csrf_token%}
                    <input class="search" type="text" name="entry" placeholder="Search Encyclopedia">
                    <input type="submit">
                </form>
                <div>
                    <a href="{% url 'Wiki:index' %}">Home</a>
                </div>
                <div>
                   <a href="{%url 'Wiki:add' %}"> Create New Page </a>
                </div>
                <div>
                    <a href="{%url 'Wiki:random'%}">
                        Random Page
                    </a>
            
                </div>
                {% block nav %}
                {% endblock %}
            </div>
            <div class="main col-lg-10 col-md-9">
                {% block body %}
                {% endblock %}
            </div>
        </div>

    </body>
</html>

encyclopedia/templates/encyclopedia/searchResult.html
{% extends "encyclopedia/layout.html" %}

{%block title%}
search result
{%endblock%}

{%block body%}

    <h1> find {{entries|length}} </h1>

    <ul>
        {% for entry in entries %}
            <li><a href="{% url 'Wiki:entryPage' entry %}"> {{ entry }}</a></li>
        {% endfor %}
    </ul>

{% endblock %}